# Introdução à Inteligência Artificial e Fundamentos de Python

## Exercícios com Python e Numpy


In [1]:
import numpy as np

Em Python, um arranjo NumPy é uma coleção modificável de elementos numéricos homogêneos eficiente numericamente.

In [2]:
l1=[1,2,3]
l2=[4,5,6]
a1=np.array(l1)
a2=np.array(l2)
print(a1.dot(a2))

32


* 1. Crie um arranjo 1D com valores entre 0 10.

In [3]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


* 2. Converta o arranho 1D criado em um arranjo 2D (matriz) com duas linhas

In [4]:
arr=arr.reshape(2,-1)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


* 3. Multiplique uma matriz 5x3por uma matriz 3x2, criadas com valores randômicos.

In [5]:
M1=np.random.random((5,3))
M2=np.random.random((3,2))
print('M1=',M1)
print('M2=',M2)
Mres=np.dot(M1,M2)
print('produto=',Mres)

M1= [[0.07694135 0.67653485 0.08618585]
 [0.88943762 0.25723257 0.68731086]
 [0.91023409 0.94068151 0.28874782]
 [0.35989826 0.05301895 0.25028315]
 [0.67116694 0.5961442  0.6278983 ]]
M2= [[0.27617685 0.16022678]
 [0.03255986 0.32141202]
 [0.46722957 0.95941186]]
produto= [[0.08354588 0.31246223]
 [0.57514949 0.88460355]
 [0.41692556 0.72521831]
 [0.21806155 0.31483089]
 [0.4981438  0.90155991]]


* 4. Extraia todos números ímpares de um arranjo 1-10

In [6]:
arr=np.arange(1,11)
impar=arr[arr%2!=0]
print(impar)

[1 3 5 7 9]


No exercício acima, o que siginifica x%2? Faça alguns testes para entender o funcionamento do comando. 
* 5. Crie uma matriz 3x3 com elementos aleatórios e calcule a soma dos elementos da diagonal.

In [7]:
M=np.random.random((3,3))
soma_diag=np.trace(M)
print(soma_diag)

0.7293264489866282


* 6. Tranforme o arranjo 1D com elementos 2,1,4.5,7.8,9,10,2,2.1,3.1,0 em uma matriz com 5x2.

In [8]:
arr=np.array([2,1,4.5,7.8,9,10,2,2.1,3.1,0])
print(len(arr))
print(arr.shape)
M=arr.reshape(-1,2) # teste com (5,-1)
print(M)

10
(10,)
[[ 2.   1. ]
 [ 4.5  7.8]
 [ 9.  10. ]
 [ 2.   2.1]
 [ 3.1  0. ]]


* 7. Empilhe dois arranjos 1D de 3 elementos verticalmente, cormando uma matriz 2x3.

In [9]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
M=np.vstack((a1,a2))
print(M)

[[1 2 3]
 [4 5 6]]


* 8. No exercício anterior, utilize np.c_ e np._r e compare os resultados com a aplicação de np.vstack.

* 9. Em Python uma Lista é uma coleção de elementos modificável. crie uma lista com elementos de tipos distintos, e modifique um deles. 

In [10]:
lst=['casa', 2, np.pi, False] # Lista com uma string, um inteiro, um real irracional e uma variável boleana. 
print(type(lst))
print(lst)
lst[2]=np.exp(1)
print(lst)
lst.append(1)
lst.append(True)
print(lst)

<class 'list'>
['casa', 2, 3.141592653589793, False]
['casa', 2, 2.718281828459045, False]
['casa', 2, 2.718281828459045, False, 1, True]


* 10. Uma tupla é uma coleção imutável de elementos

In [11]:
tupla = ("casa", 42, 3.14)

print(tupla[1])

print(tupla)

42
('casa', 42, 3.14)


In [12]:
tupla[1]=0

TypeError: 'tuple' object does not support item assignment

* 11. Crie uma matriz 3x3 com elementos 1-9

In [13]:
M=np.arange(1,10).reshape(3,3) # mesmo que (3,-1) OU (-1,3)
print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


* 12. Crie uma matrix 3x3 com 5 na diagonal principal, transponha e inverta a matriz criada.

In [14]:
M=np.eye(3)*5
print(M)
print(M.T)
print(np.linalg.inv(M))

[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]
[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]
[[0.2 0.  0. ]
 [0.  0.2 0. ]
 [0.  0.  0.2]]
