# Introdução à Inteligência Artificial e Fundamentos de Python

## Exercícios com Python e NumPy - Continuação


A Lista nativa da linguagem Python é flexível e eficiente quando se lida com estruturas de dados e algorimos:

In [1]:
lista = [
    42,                 # Integer
    "Hello World",      # String
    3.14159,            # Float
    [1, 2, 3],          # Nested List
    {"nome": "Alice"}   # Dictionary
]
print (lista)

[42, 'Hello World', 3.14159, [1, 2, 3], {'nome': 'Alice'}]


In [2]:
Nested_list=lista[3]
print(Nested_list)

[1, 2, 3]


In [3]:
Nested_list.append([4,5,6])
print(Nested_list)

[1, 2, 3, [4, 5, 6]]


In [4]:
Nested_list.pop(3)
print(Nested_list)

[1, 2, 3]


In [5]:
for i in range(10):
    Nested_list.append(3*i)
print(Nested_list)

[1, 2, 3, 0, 3, 6, 9, 12, 15, 18, 21, 24, 27]


In [6]:
del Nested_list[0:3]
print(Nested_list)

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]


In [7]:
#criação e soma dos elementos de duas listas
lista_x=list(range(10))
lista_y=list(range(10))
lista_soma=lista_x+lista_y # na verdade, + faz a concatenação das listas
print(lista_soma)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [8]:
Lista_soma=[lista_x[i]+lista_y[i] for i in range(len(lista_x))]
print(Lista_soma)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


Por outro lado, O NumPy (Numerical Python) é baseado no objeto ndarray que é muito mais eficiente para cálculos numéricos. Ao contrário das listas padrão do Python, os arrays do NumPy suportam operações rápidas sobre os elementos em paralelo, sem a necessidade de loops explícitos. Isso torna os cálculos significativamente mais rápidos e eficientes, especialmente para grandes conjuntos de dados.

In [9]:
import time
import numpy as np

# criação de listas em grandes conjuntos de dados
size = 10000000
x_G = list(range(size))
y_G = list(range(size))

start = time.time()
z_G = [x_G[i] + y_G[i] for i in range(size)]
end = time.time()
print("Python list computation time:", end - start)

# implementação NumPy 
x_G_np = np.array(x_G)
y_G_np = np.array(y_G)

start = time.time()
z_G_np = x_G_np + y_G_np
end = time.time()
print("NumPy array computation time:", end - start)

Python list computation time: 0.8246340751647949
NumPy array computation time: 0.011000871658325195


Indexação e Slicing em NumPy através de exemplos:

In [10]:
import numpy as np

arr1 = np.arange(10, 1, -2)
print("Array:", arr1)

arr2 = arr1[[3, 1, 2]]
print("Elementos índices específicos:", arr2)

Array: [10  8  6  4  2]
Elementos índices específicos: [4 8 6]


Slicing: x[start:end:step], onde:

* start: índice do elemento inicial incluído
* stop: Indice final não incluído
* step: intervalo entre elementos

In [11]:
## import numpy as np  
a = np.arange(20)
print("a[:]=",a[:])
print("a[15] =", a[15]) 
print("a[:15]=",a[:15]) # 0-14
print("a[15:] =", a[15:])# 15-19
print("a[-1:20] =", a[-1:20])# último elemento
print("a[-5:18]=", a[-5:18]) # quinto, a partir do último, até o décimo sétimo. 
print("a[::-1]=",a[::-1]) # start e stop não são fornecidos e os valores linmites são assumidos . Como step=-1, o arrajo é revertido. 
print("a[19:5:-1]=",a[19:5:-1]) 

a[:]= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
a[15] = 15
a[:15]= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
a[15:] = [15 16 17 18 19]
a[-1:20] = [19]
a[-5:18]= [15 16 17]
a[::-1]= [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
a[19:5:-1]= [19 18 17 16 15 14 13 12 11 10  9  8  7  6]


In [12]:
a = np.array( [[1, 2], [3, 4], [5, 6]] )
print( a[[0, 1, 2], [0, 0, 1]] ) #?

[1 3 6]


In [13]:
print(a[a>2])

[3 4 5 6]


In [14]:
print(a[a<4])

[1 2 3]


Seleção das linhas em uma matriz cuja soma dos elementos é um múltiplo de 10:

In [15]:
b = np.array([[5, 5], [4, 5], [16, 4]])
res = b.sum(axis=1) # soma realizada ao longo do segundo eixo:
print(res)
print(b[res % 10 == 0,:])

[10  9 20]
[[ 5  5]
 [16  4]]


Agora selecione as colunas cuja soma é múltiplo de 5:

In [16]:
res=b.sum(axis=0) # soma realizada ao longo do primeiro eixo:
print(res)
print(b[:,res % 5 == 0])

[25 14]
[[ 5]
 [ 4]
 [16]]


Exercício: Análise Matricial de Medições- Escreva uma rotina em Python, utilizando NumPY, para analisar a seguinte matriz: 

In [17]:
X = np.array([
    [12, 15, 18, 20, 22],
    [10, 14, 16, 18, 20],
    [20, 18, 15, 12, 10],
    [ 8, 10, 12, 14, 16]
])

A rotina deve:
* Calcular as dimensões da matriz
* Calcular o vetor contendo a soma das medições em cada instante, por equipamento
* Calcular a média das medições de cada equipamento
* Selecionar os equipamentos cuja soma das medições seja superior a 75
* Selecionar as colunas cuja soma seja múltipla de 2
* Multiplicar a matriz pelo vetor de ponderação p = np.array([0.8, 1.0, 1.2, 1.1, 0.9])
* Normalização por colunas: Cada coluna deve ser normalizada utilizando:
  $$X_{ij}=\frac{X-\mu}{\sigma}$$

In [18]:
X.shape

(4, 5)

A matriz possui 4 equipamentos com 5 instantes de medição.

In [19]:
# soma de todas as medidas por equipamento
soma_med=X.sum(axis=1)
print(soma_med)

[87 78 75 60]


In [20]:
# Média por equipamento:
med_equip= X.mean(axis=1)
print(med_equip)

[17.4 15.6 15.  12. ]


In [21]:
res=X[soma_med>75,:]
print(res)

[[12 15 18 20 22]
 [10 14 16 18 20]]


In [22]:
soma_col=X.sum(axis=0)
X[:,soma_col %2 ==0]

array([[12, 20, 22],
       [10, 18, 20],
       [20, 12, 10],
       [ 8, 14, 16]])

In [23]:
p = np.array([0.8, 1.0, 1.2, 1.1, 0.9])
y=X@p # equivalente a X.dot(p)
y

array([88. , 79. , 74.2, 60.6])

In [24]:
media = X.mean(axis=0)
desvio = X.std(axis=0)

X_normalizado = (X - media) / desvio
print("Média=",media)
print("Desvio Padrão=",desvio)
print("Matrix X Normalizada=", X_normalizado)

Média= [12.5  14.25 15.25 16.   17.  ]
Desvio Padrão= [4.55521679 2.86138079 2.16506351 3.16227766 4.58257569]
Matrix X Normalizada= [[-0.10976426  0.26211122  1.27017059  1.26491106  1.09108945]
 [-0.5488213  -0.08737041  0.34641016  0.63245553  0.65465367]
 [ 1.6464639   1.31055608 -0.11547005 -1.26491106 -1.52752523]
 [-0.98787834 -1.4852969  -1.5011107  -0.63245553 -0.21821789]]
